FROM %%from%%

RUN [ -z "%%epelpkgs%%" ] || yum install -y --setopt=tsflags=nodocs \
    https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum upgrade -y --setopt=tsflags=nodocs

RUN yum install -y --setopt=tsflags=nodocs \
    make automake autoconf patch which file git unzip bzip2 gcc gcc-c++ \
    glibc-devel mesa-libGL-devel alsa-lib-devel \
    libX11-devel libXext-devel libXcursor-devel libXinerama-devel libXrandr-devel libXi-devel libxkbcommon-devel \
    dbus-devel systemd-devel zlib-devel libffi-devel expat-devel libxml2-devel libtool \
    wget vim-common desktop-file-utils glib2-devel cairo-devel fuse-devel libarchive-devel %%epelpkgs%%

RUN yum install -y --setopt=tsflags=nodocs \
	"%%fpcpackage%%"

RUN yum clean all -y

CMD ["bash"]
