========================================================== 

                 Wen Quan Yi Zen Hei

                    Release Notes

----------------------------------------------------------

Dedication: 

   To Three-Leg-Cat: The "cat" who has never stopped making 
                   this font better!

----------------------------------------------------------
Summary:

    Author   : Qianqian Fang and The WenQuanYi Project Contributors
    Webpage  : http://wqy.sourceforge.net/en/
    Font Name: WenQuanYi Zen Hei
    Version  : 0.8.38 (Pangu)
    Release  : 5
    Copyright  © 2007-2009, Qianqian Fang and The WenQuanYi Project 
               Board of Trustees, All rights reserved
    License  : GPL v2 (with font embedding exception **)
               Read COPYING for details

----------------------------------------------------------

    Acknowledgment:

       This font contains the Latin/Hangul glyphs from
         un-fonts (UnDotum), Copyright (c) 1998-2004 Koanughi Un

       The Bopomofo glyphs U3100-U3127 were imported from GPL font
         cwTeX (cwming.ttf), Copyright (c) 1999,2004 Tsong-Min Wu, Tsong-Huey Wu. 
            Copyright (c) 2005 Tsong-Min Wu, Tsong-Huey Wu and Edward G.J. Lee.

       Part of the embedded bitmap glyphs were derived from
         "firefly bitmap fonts" [2], Copyright (c) 2004, Firefly 

       The mono-spaced Latin glyphs were derived from M+ M2 Light
            Copyright (c) 2002-2008 M+ FONTS PROJECT 

----------------------------------------------------------
                      Born Free
----------------------------------------------------------

Table of Content

 I.    About this font
 II.   Credits
 III.  Language Coverage
 IV.   About "The WenQuanYi Project"

----------------------------------------------------------

I. About this font

WenQuanYi Zen Hei is a Hei-Ti style (sans-serif type) Chinese 
outline font. It is designed for general purpose text formatting 
and on-screen display of Chinese characters and symbols from
many other languages. The embolden strokes of the font glyphs 
produces enhanced screen contrast, making it easier to read
recognize. The embedded bitmap glyphs further enhance on-screen 
performance, which can be enabled with the provided 
configuration files.

WenQuanYi Zen Hei provides a fairly complete coverage to Chinese 
Hanzi glyphs, including both simplified and traditional forms. 
The total glyph number in this font is over 35,000, including over 
21,000 Chinese Hanzi. This font has full coverage to GBK(CP936) 
charset, CJK Unified Ideographs, as well as the code-points 
needed for zh_cn, zh_sg, zh_tw, zh_hk, zh_mo, ja (Japanese) 
and ko (Korean) locales for fontconfig. Starting from version 
0.8, this font package has contained two font families, i.e. 
the proportionally-spaced Zen Hei, and a mono-spaced face 
named "WenQuanYi Zen Hei Mono".

----------------------------------------------------------

II. Credits

1. The spline Hanzi glyphs were created by Qianqian Fang (FangQ).

2. The Hanzi stroke data were developed by numerous contributors
   over the past 3 years. Particularly, ailantian, niqiu, FangQ, 
   Three-leg-cat, hunter, lsz, pem, twang467, zxpmyth, luoyuwen, 
   fujianwzh and farm are the key contributors.

3. The non-Hanzi glyphs, including Hangul, kana, latin etc are merged from
   UnDotum from the un-fonts project (http://kldp.net/projects/unfonts/),
   this font was released under GPL.

4. The embedded WenQuanYi bitmap song fonts were developed by WenQuanYi
   contributors and FangQ based on the bitmap fonts by firefly [2].
   The 12pt Chinese glyphs are copies of the Chinese National Standard 
   GB19966 [3]. The detailed credit for this font can be found at
        http://wenq.org/index.cgi?FirstEmperor_ChangeLog

5. The non-Hanzi glyphs for "Zen Hei Mono" were merged from 
   M+ M Type-1 Light (http://mplus-fonts.sourceforge.jp/)

6. The font file was created by Fontforge (http://fontforge.sourceforge.net/), 
    developed by George Williams.   

----------------------------------------------------------

 III. Language Coverage

The following table is based on the locale data provided by fontconfig
(generated by langcover.pl from Dejavu Project
http://dejavu.sourceforge.net/wiki/index.php/Font_utilities).

                                                ZenHei             
aa     Afar                                     100% (62/62)      
ab     Abkhazia                                  75% (68/90)      
af     Afrikaans                                100% (69/69)      
am     Amharic                                       (0/264)      
ar     Arabic                                        (0/125)      
as                                                   (0/89)       
ast    Asturian                                 100% (72/72)      
ava    Avaric                                   100% (67/67)      
ay     Aymara                                   100% (60/60)      
az     Azerbaijani                               90% (134/148)    
az-ir  Azerbaijani in Iran                           (0/130)      
ba     Bashkir                                   78% (64/82)      
bam    Bambara                                  100% (60/60)      
be     Byelorussian                             100% (68/68)      
bg     Bulgarian                                100% (60/60)      
bh     Bihari (Devanagari script)                    (0/68)       
bho    Bhojpuri (Devanagari script)                  (0/68)       
bi     Bislama                                  100% (58/58)      
bin    Edo or Bini                               92% (72/78)      
bn     Bengali                                       (0/89)       
bo     Tibetan                                       (0/95)       
br     Breton                                   100% (64/64)      
bs     Bosnian                                  100% (62/62)      
bua    Buriat (Buryat)                           94% (66/70)      
ca     Catalan                                  100% (74/74)      
ce     Chechen                                  100% (67/67)      
ch     Chamorro                                 100% (58/58)      
chm    Mari (Lower Cheremis / Upper Cheremis)    86% (66/76)      
chr    Cherokee                                      (0/85)       
co     Corsican                                 100% (85/85)      
cs     Czech                                    100% (82/82)      
cu     Old Church Slavonic                       71% (74/103)     
cv     Chuvash                                   91% (68/74)      
cy     Welsh                                     89% (70/78)      
da     Danish                                   100% (70/70)      
de     German                                   100% (60/60)      
dz     Dzongkha                                      (0/95)       
el     Greek                                    100% (70/70)      
en     English                                  100% (73/73)      
eo     Esperanto                                100% (64/64)      
es     Spanish                                  100% (67/67)      
et     Estonian                                 100% (64/64)      
eu     Basque                                   100% (56/56)      
fa     Persian                                       (0/129)      
fi     Finnish                                  100% (63/63)      
fj     Fijian                                   100% (52/52)      
fo     Faroese                                  100% (68/68)      
fr     French                                   100% (85/85)      
ful    Fulah (Fula)                             100% (62/62)      
fur    Friulian                                 100% (66/66)      
fy     Frisian                                  100% (75/75)      
ga     Irish                                     82% (66/80)      
gd     Scots Gaelic                             100% (70/70)      
gez    Ethiopic (Geez)                               (0/218)      
gl     Galician                                 100% (66/66)      
gn     Guarani                                   97% (68/70)      
gu     Gujarati                                      (0/78)       
gv     Manx Gaelic                              100% (54/54)      
ha     Hausa                                    100% (60/60)      
haw    Hawaiian                                 100% (63/63)      
he     Hebrew                                        (0/27)       
hi     Hindi (Devanagari script)                     (0/68)       
ho     Hiri Motu                                100% (52/52)      
hr     Croatian                                 100% (62/62)      
hu     Hungarian                                100% (70/70)      
hy     Armenian                                      (0/77)       
ia     Interlingua                              100% (52/52)      
ibo    Igbo                                      89% (52/58)      
id     Indonesian                               100% (54/54)      
ie     Interlingue                              100% (52/52)      
ik     Inupiaq (Inupiak, Eskimo)                100% (68/68)      
io     Ido                                      100% (52/52)      
is     Icelandic                                100% (70/70)      
it     Italian                                  100% (73/73)      
iu     Inuktitut                                     (0/161)      
ja     Japanese                                 100% (6538/6538)  
ka     Georgian                                      (0/33)       
kaa    Kara-Kalpak (Karakalpak)                  84% (66/78)      
ki     Kikuyu                                   100% (56/56)      
kk     Kazakh                                    84% (65/77)      
kl     Greenlandic                              100% (81/81)      
km     Khmer                                         (0/70)       
kn     Kannada                                       (0/80)       
ko     Korean                                   100% (2443/2443)  
kok    Kokani (Devanagari script)                    (0/68)       
ks     Kashmiri (Devanagari script)                  (0/68)       
ku     Kurdish                                   90% (58/64)      
ku-ir  Kurdish in Iran                               (0/32)       
kum    Kumyk                                    100% (66/66)      
kv     Komi (Komi-Permyak/Komi-Siryan)           97% (68/70)      
kw     Cornish                                  100% (64/64)      
ky     Kirgiz                                    94% (66/70)      
la     Latin                                    100% (68/68)      
lb     Luxembourgish (Letzeburgesch)            100% (75/75)      
lez    Lezghian (Lezgian)                       100% (67/67)      
ln     Lingala                                   96% (78/81)      
lo     Lao                                           (0/65)       
lt     Lithuanian                               100% (70/70)      
lv     Latvian                                  100% (78/78)      
mg     Malagasy                                 100% (56/56)      
mh     Marshallese                              100% (62/62)      
mi     Maori                                     96% (62/64)      
mk     Macedonian                                90% (38/42)      
ml     Malayalam                                     (0/78)       
mn     Mongolian                                     (0/130)      
mo     Moldavian                                100% (128/128)    
mr     Marathi (Devanagari script)                   (0/68)       
mt     Maltese                                  100% (72/72)      
my     Burmese (Myanmar)                             (0/48)       
nb     Norwegian Bokmal                         100% (70/70)      
nds    Low Saxon                                100% (59/59)      
ne     Nepali (Devanagari script)                    (0/68)       
nl     Dutch                                    100% (83/83)      
nn     Norwegian Nynorsk                        100% (76/76)      
no     Norwegian (Bokmal)                       100% (70/70)      
ny     Chichewa                                 100% (54/54)      
oc     Occitan                                  100% (70/70)      
om     Oromo or Galla                           100% (52/52)      
or     Oriya                                         (0/79)       
os     Ossetic                                  100% (66/66)      
pa     Punjabi (Gurumukhi script)                    (0/63)       
pl     Polish                                   100% (70/70)      
ps-af  Pashto in Afghanistan                         (0/49)       
ps-pk  Pashto in Pakistan                            (0/49)       
pt     Portuguese                               100% (83/83)      
rm     Rhaeto-Romance (Romansch)                100% (66/66)      
ro     Romanian                                 100% (62/62)      
ru     Russian                                  100% (66/66)      
sa     Sanskrit (Devanagari script)                  (0/68)       
sah    Yakut                                     86% (66/76)      
sco    Scots                                    100% (56/56)      
se     North Sami                               100% (66/66)      
sel    Selkup (Ostyak-Samoyed)                  100% (66/66)      
sh     Serbo-Croatian                           100% (76/76)      
si     Sinhala (Sinhalese)                           (0/77)       
sk     Slovak                                   100% (86/86)      
sl     Slovenian                                100% (62/62)      
sm     Samoan                                   100% (53/53)      
sma    South Sami                               100% (60/60)      
smj    Lule Sami                                100% (60/60)      
smn    Inari Sami                               100% (68/68)      
sms    Skolt Sami                               100% (80/80)      
so     Somali                                   100% (52/52)      
sq     Albanian                                 100% (56/56)      
sr     Serbian                                  100% (76/76)      
sv     Swedish                                  100% (68/68)      
sw     Swahili                                  100% (52/52)      
syr    Syriac                                        (0/45)       
ta     Tamil                                         (0/48)       
te     Telugu                                        (0/80)       
tg     Tajik                                     84% (66/78)      
th     Thai                                          (0/87)       
ti-er  Eritrean Tigrinya                             (0/256)      
ti-et  Ethiopian Tigrinya                            (0/282)      
tig    Tigre                                         (0/221)      
tk     Turkmen                                   89% (66/74)      
tl     Tagalog                                       (0/19)       
tn     Tswana                                   100% (56/56)      
to     Tonga                                    100% (53/53)      
tr     Turkish                                  100% (70/70)      
ts     Tsonga                                   100% (52/52)      
tt     Tatar                                     86% (66/76)      
tw     Twi                                       90% (66/73)      
tyv    Tuvinian                                  94% (66/70)      
ug     Uighur                                        (0/125)      
uk     Ukrainian                                 97% (70/72)      
ur     Urdu                                          (0/145)      
uz     Uzbek                                     88% (60/68)      
ven    Venda                                     83% (52/62)      
vi     Vietnamese                                49% (96/194)     
vo     Volapuk                                  100% (54/54)      
vot    Votic                                    100% (62/62)      
wa     Walloon                                  100% (70/70)      
wen    Sorbian languages (lower and upper)      100% (76/76)      
wo     Wolof                                    100% (66/66)      
xh     Xhosa                                    100% (52/52)      
yap    Yapese                                   100% (58/58)      
yi     Yiddish                                       (0/27)       
yo     Yoruba                                    87% (104/119)    
zh-936 GBK Chinese national standard            100% (21920/21920)
zh-cn  Chinese (simplified)                     100% (6765/6765)  
zh-hk  Chinese Hong Kong Supplementary Character Set 100% (2213/2213)  
zh-mo  Chinese in Macau                         100% (2213/2213)  
zh-sg  Chinese in Singapore                     100% (6765/6765)  
zh-tw  Chinese (traditional)                    100% (13063/13063)
zu     Zulu                                     100% (52/52)      
  
----------------------------------------------------------

 IV. About The WenQuanYi Project

The Wen Quan Yi Project[1] was founded by Qianqian Fang[5] in 
Oct. 2004. The goal of this project is to create a highly efficient 
collaborative environment for open-source type-face development. 
The initial focus of the project is to create high quality bitmap 
character glyphs and outline fonts for all 70,000+ CJK characters 
currently encoded by the Unicode Consortium. 

The Wen Quan Yi Project uses Wiki[1] as the primary 
development tool for glyph creation, documentation
and coordinations. The Wen Quan Yi wiki also supports
glyph CVS and nightly build.

The embodiment of the project consists of a 
"Steering Committee" by the core members, a "Team B" 
for bitmap Chinese font development and a "Team V" 
for outline font development. Need to mention, a large 
number of anonymous contributors also participate in our 
development through our Wiki website and their 
contributions are non-negligible.



[1] The WenQuanYi Project Homepage
      http://wqy.sourceforge.net/            (Chinese version)
      http://wqy.sourceforge.net/en/         (English version)
      http://sourceforge.net/projects/wqy/   (Sourceforge project)
      http://wenq.org/                       (Development site)
      http://wenq.org/forum/                 (User forum)
      http://wenq.org/gallery/               (Screenshot gallery)

[2] Firefly bitmap font
      http://www.study-area.org/apt/firefly-font/

[3] Chinese National Standard GB19966-2005 (mandatory)
     http://www.standardcn.com/standard_plan/list_standard_content.asp?
             stand_id=GB@19966-2005

[4] The Unicode Consortium
     http://www.unicode.org/

[5] Qianqian Fang homepage
     http://nmr.mgh.harvard.edu/~fangq/

----------------------------------------------------------

** GPL v2 license with font embedding exception:

http://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#FontException

As a special exception, if you create a document which uses this
font, and embed this font or unaltered portions of this font into 
the document, this font does not by itself cause the resulting 
document to be covered by the GNU General Public License. This 
exception does not however invalidate any other reasons why the 
document might be covered by the GNU General Public License. If you 
modify this font, you may extend this exception to your version of 
the font, but you are not obligated to do so. If you do not wish to 
do so, delete this exception statement from your version.

==========================================================
