###################################
# theme developed by Daniel20     #
# for https:\\ultrastar-es.org    #
# visit us to get songs, plugins, #
# themes and more...              #
#                                 #
# *some icons belongs to          #
#  https://www.iconfinder.com/    #
#  under Creative Common license  #
###################################

#Video credits to: AA VFX https://www.youtube.com/watch?v=X36DOTEzjHw

###############
[Skin]
Theme=Neon
Name=Magma
Color=Red

[Textures]
TitleBG	       = [bg-main]magma.webm
MainBG         = [bg-main]magma.webm
SongBG         = [bg-main]magma.webm
ScoreScreenBG  = [bg-main]magma.webm
Top5BG         = [bg-main]magma.webm
OptionsBG      = [bg-main]magma.webm
PartyBG        = [bg-main]magma.webm
